### ISSUE TITLE
Safe transfers

### ISSUE THREAD

**Issue by NGR-KLR** [realSamiel/NGRcoin#12]
How do we ensure that somebody sends the ngr coins they sent the hash of?
what's to stop me sending you 10 valid hashes, but 10 random strings that don't create those hashes?

**Comment by 10135** [comment]
NGR is a trust based cryptocurrency
you must trust everyone you transact with and just hope you aren't niggers and steal your NGRs

**Comment by realSamiel** [comment]
you can check the random strings.

**Comment by NGR-KLR** [comment]
isnt' that a bit to late at that point? you'll have already finished the trade deal
either way, making it trust based is good enough

**Comment by realSamiel** [comment]
If you don't get the actual NGR the transaction never happened.
So just don't give them the thing they didn't pay for.

**Comment by NGR-KLR** [comment]
i take that back, you were right, just check the random strings
