### ISSUE TITLE
What does NGR stand for

### ISSUE THREAD

**Issue by vxiiduu** [realSamiel/NGRcoin#15]
I can't find any information in the docs about what "NGR" stands for. I am planning to mention NGR Coin in my upcoming research paper at a top 5 university, and our academic citation policy requires spelling out the full wording of every abbreviation used. Thanks.

**Comment by RockyBukake** [comment]
N

**Comment by realSamiel** [comment]
The normie answere is Network Generated Recource. But that is obvious bullshit.
