### ISSUE TITLE
 expiry time on coins

### ISSUE THREAD

**Issue by realSamiel** [realSamiel/NGRcoin#23]
I don't see the point of this or how it could be implemented but we need to resolve this point of contention.

**Comment by kosti357** [comment]
Expiration dates will make inflation impossible since people cannot save up huge amounts of NGR and this will encourage spending. This would be very good for longevity. 
Additionaly NGR along with Chinas e-CNY will be among the worlds first exiration date currencies, which is pretty cool.

**Comment by realSamiel** [comment]
shouldn't we just increase the difficulty, adding more Gs?

**Comment by NGR-KLR** [comment]
this is perhaps a different issue, but would we add more Gs or more Rs? because more Rs would mean the current scripts haven't been missing move valuable coins.

**Comment by realSamiel** [comment]
it would also be easyer to implement
hmm.jpg

**Comment by NGR-KLR** [comment]
if we just increase difficulty, we will end up with wallets that just keep growing, but we can't spend the worhless coins at the bottom. expiry would clear them out when they become useless, potentially saving megabytes of space. we wanted to avoid a blockchain. it'd be ashame to just have a wallet file the size of a blockchain.

**Comment by realSamiel** [comment]
let the people set max sizes for their wallets?

**Comment by NGR-KLR** [comment]
that would cause it to regain value though, a 36 day expiry time (from IRC discussion) seems like the best way to solve this issue. closing for now. re-open if you think of something
