### ISSUE TITLE
v3

### ISSUE THREAD

**Issue by 10135** [realSamiel/NGRcoin#44]
seeing as people want to implement things like difficulty & coin expiration to make NGR more like a "real crypto"
how would people feel about making a v3 that actually uses a blockchain so it can be traded just like any other crypto
or is that cringe?

all we have to do is standardize some sort of transaction format with public /private keys like bitcoin, a network protocol to submit said transactions to willing miners, and lastly a block format where the difficulty of the block (instead of being some amount of 0s like it is in bitcoin) is 0xNIGGER where the amount of Gs determine the difficulty. It would effectively work just like bitcoin. Perhaps we could discuss some ideas for how to make it more unique while still using a blockchain.

**Comment by 10135** [comment]
idk maybe this is overdoing it for a shitposting coin
but i'd be down for it if other people are

**Comment by realSamiel** [comment]
I was hoping that our doublespend enabled shitcoin could actually have some shitposting usecases and spawn a little ecosystem.

**Comment by 10135** [comment]
yeah i hoped so too. I honestly really like the "double spend but not double own" idea but the more i try to think about usecases for it the less i like it.

Would you have anything against it if i start a v3 branch & just work on it myself? (others can join if they want to)
