### ISSUE TITLE
update NGR to new protocol

### ISSUE THREAD

**Issue by 10135** [realSamiel/NGRcoin#5]
Idk if someone is already working on this but someone needs to update the readme to the new protocol that prevents coin forging (also the tools need to be updated). New protocol:

one valid NGR is a base64 encoded string which contain the word "nigger" anywhere in it, and whose sha256 hash contains the following nighex values anywhere (has to be in order this) N I G G E R (base10 values:  10, 11, 12, 12, 13, 14)

What you put in the base64 encoded string is unspecified. Anything is valid as long as it follows the above criteria. This allow people to put funny stuff in the input of the string.

Also clarification: a NGR coin is the base64 encoded string itself, not the input to the string, nor the hash of the string.

**Comment by realSamiel** [comment]
all of the sha256 based stuff goes into the NGRv2 branch.
If you could take care of the readmes a bit, that would be great.

**Comment by 10135** [comment]
alright
also now that we are on the topic of branches could we change the main branch to master
