### ISSUE TITLE
base64 string requirement in NGRv2

### ISSUE THREAD

**Issue by 10135** [realSamiel/NGRcoin#7]
so there seem to be some disagreement about whether NGRv2 coins should require that the base64 encoded string itself also should contain the word "nigger" or whether it should only require that the hash of the string contain the nighex value of 0xNIGGER.

Personally i think it should require both. As its the actual base64 encoded string we store in the wallet, we should be able to see the word "nigger".

**Comment by realSamiel** [comment]
The problem is that this increase the difficulty by a lot. And since you need the hashes for secure transactions, I would suggest that both are stored in the wallet so you will be able to see the niggers in your wallet.

**Comment by NGR-KLR** [comment]
Unless we want the coin to be difficult to mine, it should only be in the sha hash. Storing both in the wallet would also simplify the transfer script, so that's good too.
I've been banned by the jannies for a day, so I can't post in the thread anymore, only here.

**Comment by 10135** [comment]
yeah ok maybe you guys are right

**Comment by realSamiel** [comment]
it seems that 4 thread isn't exactly on our side
what do?
I still think that the difficulty is important.

**Comment by NGR-KLR** [comment]
In the new thread people seem to be agreeing with the v2 switch

**Comment by realSamiel** [comment]
do we shut down the discussion and dictate that only the hash has to include any special phrase?

**Comment by 10135** [comment]
fuck em i actually like the idea of only requiring the hash to have a certain value

that way we can still have the concept of "rare" NGRs (like they would be determined by whether the base64 encoded string has some cool values)

**Comment by 10135** [comment]
maybe we should remove the line that says 0xNEGRO is also valid

**Comment by realSamiel** [comment]
Ok, I guess we reached a decision. sha256 only!
